Add tests and Replace email Logic in REST routes
corona-school/backend_new pull request #14
Opened 2021-04-10 18:41 UTC by ayushpandey8439

Hey, I have written a few tests which check both backend and front end functionality. I will extend these further for the other routes but it should give an idea of how things are being handled and hopefully you can get an idea of how to write tests too.

2021-04-11 19:38 UTC, lsc0498 requested changes
Please remove all the testing and debugging artefacts like comments and logs before merging into master 😉

2021-04-11 19:38 UTC, lsc0498 commented on logs/jobs.log
> +[2021-04-10T18:44:23.658] [INFO] default - Started Notification Handler
Don't commit logs 😉

2021-04-11 19:38 UTC, lsc0498 commented on services/authService.ts
> +            /*sendNotification(
Rather delete lines than commenting them out. We can always rollback changes using Git if we like :)

2021-04-11 19:38 UTC, lsc0498 commented on services/authService.ts
> +            /*sendNotification(user.email, {
Same as above.

2021-04-11 19:38 UTC, lsc0498 commented on services/userService.ts
> +            const updateEmailNoti = new verification(updateEmail.email, {
Full variable names look better ;D

2021-04-11 19:38 UTC, lsc0498 commented on services/userService.ts
> +            /*sendNotification(updateEmail.email, {
Remove commented out lines.

2021-04-11 19:38 UTC, lsc0498 commented on services/userService.ts
> +            /*sendText(
Same as before.

2021-04-11 19:38 UTC, lsc0498 commented on services/userService.ts
> +            const phoneChangeNoti = new test_sms(
What ist this? Test instances should actually not appear in this service file.

2021-04-11 19:38 UTC, lsc0498 commented on services/notificationHandler.ts
> +                const sendText = new test_sms(
Please don't put test cases in here.

2021-04-12 15:52 UTC, ayushpandey8439 commented on services/notificationHandler.ts
> +                const sendText = new test_sms(
test_sms is just an initial template that I created for mailjet since I did not have a specific use case for sms notifications. Ideally the will be replaced by specific names like 'sendUserVerifiedSms'. These do not correspond to test cases though.

2021-04-12 16:40 UTC, lsc0498 approved these changes
Thank you!

2021-04-12 16:43 UTC, merged